BOT_NAME = "machine_catalog_scraper"
SPIDER_MODULES = ["machine_catalog_scraper.spiders"]
NEWSPIDER_MODULE = "machine_catalog_scraper.spiders"

ROBOTSTXT_OBEY = True
DOWNLOAD_DELAY = 2
CONCURRENT_REQUESTS_PER_DOMAIN = 2
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
RETRY_ENABLED = True
RETRY_HTTP_CODES = [429, 500, 502, 503, 504]
LOG_LEVEL = "INFO"
USER_AGENT = "MachineCatalogBot"
